# Generated by Django 5.0.7 on 2025-05-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_dae',
            new_name='hire_date',
        ),
    ]
